import { awscdk, javascript, JsonFile } from 'projen';

const cdkVersion = '2.91.0';
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'New Relic',
  authorAddress: 'https://newrelic.com',
  authorOrganization: true,
  cdkVersion,
  defaultReleaseBranch: 'main',
  jsiiVersion: '~5.0.0',
  name: '@newrelic/cdk-l2-dashboards',
  projenrcTs: true,
  repositoryUrl: 'https://github.com/newrelic/cdk-l2-dashboards.git',
  description: 'AWS CDK Construct Library for New Relic Dashboards. Generated by projen.',
  license: 'Apache-2.0',
  deps: [
    'graphql',
    'graphql-request',
  ],
  devDeps: [
    'esbuild',
    'constructs',
  ],
  bundledDeps: [
    'graphql',
    'graphql-request',
  ],
  stability: 'experimental',
  gitignore: [
    '.idea',
    'scratch',
    'graphql.config.yml',
    'cdk.out',
    'package-lock.json',
    'progen',
    'local',
  ],

  keywords: [
    'cdk',
    'aws-cdk',
    'awscdk',
    'cloudformation',
    'cfn',
    'extensions',
    'constructs',
    'cfn-resources',
    'cloudformation-registry',
    'l2',
    'newrelic',
    'new-relic',
  ],
  npmAccess: javascript.NpmAccess.PUBLIC,
  majorVersion: 1,
  docgen: true,
  releaseToNpm: true,
});

new JsonFile(project, 'cdk.json', {
  obj: {
    app: 'npx ts-node --prefer-ts-exts src/integ.default.ts',
  },
});

project.addPackageIgnore('/local/**/*');
//project.addPackageIgnore('./local/setupJest.ts');
project?.jest?.addSetupFile('<rootDir>/local/setupJest.ts');
project?.jest?.addSetupFileAfterEnv('<rootDir>/local/setupJest.ts');
project?.eslint?.addRules({
  // '@typescript-eslint/indent': ['error', 3],
  // 'quotes': ['error', 'double'],
  'no-trailing-spaces': ['error', { skipBlankLines: true }],
  'max-len': ['error', { code: 240 }],
});

// ALWAYS LAST!
project.synth();
